In [1]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [3]:
import numpy as np
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [5]:
import numpy as np
arr =np.array([
    [1,2,3,4,5],
    [2,3,4,5,6],
    [3,4,5,6,7],
    [4,5,6,7,8],
    [5,6,7,8,9],
    [6,7,8,9,0]
])
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]
 [5 6 7 8 9]
 [6 7 8 9 0]]


In [7]:
import numpy as np
arr = np.zeros([1,2,3])
print(arr)

[[[0. 0. 0.]
  [0. 0. 0.]]]


In [9]:
import numpy as np
arr = np.zeros([1,2,3])
arr1 = np.ones([2,3,4])
print(arr)
print(arr1)

[[[0. 0. 0.]
  [0. 0. 0.]]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [14]:
import numpy as np
arr = np.full ((4,4),2)
print(arr)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]
